<?php
echo "<center><table class='table-striped' style='width:40%;>";
        echo "<tbody class='table-hover'>";
            echo "<tr>";
                echo  "<td colspan='2'><br><center>Datos de Usuario</center><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='48%'>Usuario:</td><td width='50%'>".$row['usuario']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Correo:</td><td width='50%'>".$row['correo']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td colspan='2'><br><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td colspan='2'><br><center>Datos de Facturacion</center><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Nombre:</td><td width='50%'>".$row['c_nombre']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Apellidos:</td><td width='50%'>".$row['c_apellidos']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Direccion:</td><td width='50%'>".$row['c_direccion']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Ciudad:</td><td width='50%'>".$row['c_ciudad']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Provincia:</td><td width='50%'>".$row['c_provincia']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Telefono:</td><td width='50%'>".$row['c_telefono']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Fecha Facturacion:</td><td width='50%'>".$row['c_ffact']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Numero Tarjeta:</td><td width='50%'>".$row['c_tarjeta']."</td>";
            echo "</tr>";
                echo "<tr>";
                echo  "<td colspan='2'><br><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td colspan='2'><br><center>Datos de Envío</center><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Nombre:</td><td width='50%'>".$row['e_nombre']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Apellidos:</td><td width='50%'>".$row['e_apellidos']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Direccion:</td><td width='50%'>".$row['e_direccion']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Ciudad:</td><td width='50%'>".$row['e_ciudad']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Provincia:</td><td width='50%'>".$row['e_provincia']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Telefono:</td><td width='50%'>".$row['e_telefono']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Fecha envio:</td><td width='50%'>".$row['c_fenv']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td colspan='2'><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td colspan='2'><br><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td colspan='2'><br><center>Datos de Mensaje</center><br></td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Mensaje:</td><td width='50%'>".$row['mensaje']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Personalizado:</td><td width='50%'>".$row['personalizado']."</td>";
            echo "</tr>";
            echo "<tr>";
                echo  "<td width='50%'>Precio:</td><td width='50%'>".$row['precio']."€</td>";
            echo "</tr>";
    echo "</tbody>";
echo "</table></center>";




?>